# Words and phonetics data
words_phonetics = [
    {"word":"analyze", "syllable_word":"an·a·lyze", "phonetic":"ˈæn·ə·ˌlaɪz", "japanese_synonym":"分析（ぶんせき）する"},
    {"word":"concept", "syllable_word":"con·cept", "phonetic":"ˈkɑn·sɛpt", "japanese_synonym":"概念 (がいねん) "},
    {"word":"context", "syllable_word":"con·text", "phonetic":"ˈkɑn·tɛkst", "japanese_synonym":"文脈 (ぶんみゃく) "},
    {"word":"derive", "syllable_word":"de·rive", "phonetic":"dɪˈraɪv", "japanese_synonym":"導出（どうしゅつ）する"},
    {"word":"empirical", "syllable_word":"em·pir·i·cal", "phonetic":"ɛmˈpɪr·ɪ·kəl", "japanese_synonym":"経験的(けいけんてき）"},
    {"word":"framework", "syllable_word":"frame·work", "phonetic":"ˈfreɪmˌwɜrk", "japanese_synonym":"枠組（わくぐ）み"},
    {"word":"hypothesis", "syllable_word":"hy·poth·e·sis", "phonetic":"haɪˈpɑθ·ə·sɪs", "japanese_synonym":"仮説 (かせつ)"},
    {"word":"implement", "syllable_word":"im·ple·ment", "phonetic":"ˈɪm·plə·mənt", "japanese_synonym":"実装 (じっそう）する"},
    {"word":"infer", "syllable_word":"in·fer", "phonetic":"ɪnˈfɜr", "japanese_synonym":"推測 (すいそく）する"},
    {"word":"mechanism", "syllable_word":"mech·an·ism", "phonetic":"ˈmɛk·əˌnɪz·əm", "japanese_synonym":"メカニズム（めかにずむ) ）"},
    {"word":"parameter", "syllable_word":"pa·ram·e·ter", "phonetic":"pəˈræm·ɪ·tər", "japanese_synonym":"パラメータ（ぱらめーた）"},
    {"word":"protocol", "syllable_word":"pro·to·col", "phonetic":"ˈproʊ·təˌkɔl", "japanese_synonym":"プロトコル（ぷろとこる）"},
    {"word":"quantitative", "syllable_word":"quan·ti·ta·tive", "phonetic":"ˈkwɑn·tɪˌteɪ·tɪv", "japanese_synonym":"定量的（ていりょうてき）"},
    {"word":"refine", "syllable_word":"re·fine", "phonetic":"rɪˈfaɪn", "japanese_synonym":"精製（せいせい）する"},
    {"word":"simulate", "syllable_word":"sim·u·late", "phonetic":"ˈsɪm·jʊˌleɪt", "japanese_synonym":"シミュレート（しみゅれーと）する"},
    {"word":"theoretical", "syllable_word":"the·o·ret·i·cal", "phonetic":"ˌθi·əˈrɛt·ɪ·kəl", "japanese_synonym":"理論的（りろんてき）"},
    {"word":"validate", "syllable_word":"val·i·date", "phonetic":"ˈvæl·ɪˌdeɪt", "japanese_synonym":"検証（けんしょう）する"},
    {"word":"variable", "syllable_word":"var·i·a·ble", "phonetic":"ˈvɛr·i·ə·bəl", "japanese_synonym":"変数（へんすう）"},
    {"word":"aggregate", "syllable_word":"ag·gre·gate", "phonetic":"ˈæg·rɪˌgeɪt", "japanese_synonym":"集約（しゅうやく）する"},
    {"word":"coherent", "syllable_word":"co·her·ent", "phonetic":"koʊˈhɪr·ənt", "japanese_synonym":"首尾一貫（しゅびいっかん）"},
    {"word":"complement", "syllable_word":"com·ple·ment", "phonetic":"ˈkɒm·pləˌmɛnt", "japanese_synonym":"補完（ほかん）する"},
    {"word":"constrain", "syllable_word":"con·strain", "phonetic":"kənˈstreɪn", "japanese_synonym":"制約（せいやく）する"},
    {"word":"decentralize", "syllable_word":"de·cen·tral·ize", "phonetic":"diːˈsɛn·trəˌlaɪz", "japanese_synonym":"分散（ぶんさん）する"},
    {"word":"dichotomy", "syllable_word":"di·chot·o·my", "phonetic":"daɪˈkɑt·əˌmi", "japanese_synonym":"二分法（にぶんほう）"},
    {"word":"disseminate", "syllable_word":"dis·sem·i·nate", "phonetic":"dɪˈsɛm·ɪˌneɪt", "japanese_synonym":"普及（ふきゅう）する"},
    {"word":"fluctuate", "syllable_word":"fluc·tu·ate", "phonetic":"ˈflʌk·tʃuˌeɪt", "japanese_synonym":"変動（へんどう）する"},
    {"word":"heuristic", "syllable_word":"heu·ris·tic", "phonetic":"hjuːˈrɪs·tɪk", "japanese_synonym":"ヒューリスティック（ひゅーりすてぃっく）"},
    {"word":"innovate", "syllable_word":"in·no·vate", "phonetic":"ˈɪn·əˌveɪt", "japanese_synonym":"革新（かくしん）する"},
    {"word":"integrate", "syllable_word":"in·te·grate", "phonetic":"ˈɪn·tɪˌgreɪt", "japanese_synonym":"統合（とうごう）する"},
    {"word":"mediate", "syllable_word":"me·di·ate", "phonetic":"ˈmiː·diˌeɪt", "japanese_synonym":"仲介（ちゅうかい）する"},
    {"word":"normative", "syllable_word":"nor·ma·tive", "phonetic":"ˈnɔr·məˌtɪv", "japanese_synonym":"規範的（きはんてき）"},
    {"word":"paradigm", "syllable_word":"par·a·digm", "phonetic":"ˈpær·əˌdaɪm", "japanese_synonym":"パラダイム（ぱらだいむ）"},
    {"word":"pertinent", "syllable_word":"per·ti·nent", "phonetic":"ˈpɜr·tɪ·nənt", "japanese_synonym":"適切（てきせつ）な"},
    {"word":"proliferate", "syllable_word":"pro·lif·er·ate", "phonetic":"prəˈlɪf·əˌreɪt", "japanese_synonym":"増殖（ぞうしょく）する"},
    {"word":"synthesize", "syllable_word":"syn·the·size", "phonetic":"ˈsɪn·θəˌsaɪz", "japanese_synonym":"合成（ごうせい）する"},
    {"word":"transcend", "syllable_word":"tran·scend", "phonetic":"trænˈsɛnd", "japanese_synonym":"超越（ちょうえつ）する"},
    {"word":"underlying", "syllable_word":"un·der·ly·ing", "phonetic":"ˌʌn·dərˈlaɪ·ɪŋ", "japanese_synonym":"基本的（きほんてき）な"},
    {"word":"viability", "syllable_word":"vi·a·bil·i·ty", "phonetic":"ˌvaɪ·əˈbɪl·ɪ·ti", "japanese_synonym":"実現可能性（じつげんかのうせい）"},
    {"word":"volatility", "syllable_word":"vol·a·til·i·ty", "phonetic":"ˌvɑl·əˈtɪl·ɪ·ti", "japanese_synonym":"揮発性（きはつせい）"},
    {"word":"ameliorate", "syllable_word":"a·mel·io·rate", "phonetic":"əˈmiːl·jəˌreɪt", "japanese_synonym":"改善（かいぜん）する"},
    {"word":"catalyze", "syllable_word":"cat·a·lyze", "phonetic":"ˈkæt·əˌlaɪz", "japanese_synonym":"触媒（しょくばい）する"},
    {"word":"converge", "syllable_word":"con·verge", "phonetic":"kənˈvɜrʤ", "japanese_synonym":"収束（しゅうそく）する"},
    {"word":"delineate", "syllable_word":"de·lin·e·ate", "phonetic":"dɪˈlɪn·iˌeɪt", "japanese_synonym":"描写（びょうしゃ）する"},
    {"word":"demarcate", "syllable_word":"de·mar·cate", "phonetic":"dɪˈmɑrˌkeɪt", "japanese_synonym":"区分（くぶん）する"},
    {"word":"dichotomize", "syllable_word":"di·chot·o·mize", "phonetic":"daɪˈkɑt·əˌmaɪz", "japanese_synonym":"二分（にぶん）する"},
    {"word":"equivocate", "syllable_word":"e·quiv·o·cate", "phonetic":"ɪˈkwɪv·əˌkeɪt", "japanese_synonym":"曖昧（あいまい）な"},
    {"word":"extrapolate", "syllable_word":"ex·trap·o·late", "phonetic":"ɪkˈstræp·əˌleɪt", "japanese_synonym":"外挿（がいそう）する"},
    {"word":"facilitate", "syllable_word":"fa·cil·i·tate", "phonetic":"fəˈsɪl·ɪˌteɪt", "japanese_synonym":"容易（ようい）にする"},
    {"word":"galvanize", "syllable_word":"gal·va·nize", "phonetic":"ˈgæl·vəˌnaɪz", "japanese_synonym":"活気づける（かっきづける）"},
    {"word":"harmonize", "syllable_word":"har·mo·nize", "phonetic":"ˈhɑr·məˌnaɪz", "japanese_synonym":"調和（ちょうわ）する"},
    {"word":"ideate", "syllable_word":"ide·ate", "phonetic":"ˈaɪ·diˌeɪt", "japanese_synonym":"発想（はっそう）する"},
    {"word":"juxtapose", "syllable_word":"jux·ta·pose", "phonetic":"ˈʤʌk·stəˌpoʊz", "japanese_synonym":"並置（へいち）する"},
    {"word":"legitimize", "syllable_word":"le·git·i·mize", "phonetic":"ləˈʤɪt·əˌmaɪz", "japanese_synonym":"合法化（ごうほうか）する"},
    {"word":"marginalize", "syllable_word":"mar·gin·al·ize", "phonetic":"ˈmɑr·ʤɪn·əˌlaɪz", "japanese_synonym":"周辺化（しゅうへんか）する"},
    {"word":"nuance", "syllable_word":"nu·ance", "phonetic":"ˈnuː·ɑns", "japanese_synonym":"ニュアンス（にゅあんす）"},
    {"word":"obfuscate", "syllable_word":"ob·fus·cate", "phonetic":"ˈɑb·fʌˌskeɪt", "japanese_synonym":"混乱（こんらん）させる"},
    {"word":"permeate", "syllable_word":"per·me·ate", "phonetic":"ˈpɜr·miˌeɪt", "japanese_synonym":"浸透（しんとう）する"},
    {"word":"reconcile", "syllable_word":"rec·on·cile", "phonetic":"ˈrɛk·ənˌsaɪl", "japanese_synonym":"調停（ちょうてい）する"},
    {"word":"saturate", "syllable_word":"sat·u·rate", "phonetic":"ˈsætʃ·əˌreɪt", "japanese_synonym":"飽和（ほうわ）する"},
    {"word":"triangulate", "syllable_word":"tri·an·gu·late", "phonetic":"traɪˈæŋ·ɡjʊˌleɪt", "japanese_synonym":"三角測量（さんかくそくりょう）する"},
    {"word":"underscore", "syllable_word":"un·der·score", "phonetic":"ˌʌn·dərˈskɔr", "japanese_synonym":"強調（きょうちょう）する"},
    {"word":"venerate", "syllable_word":"ven·er·ate", "phonetic":"ˈvɛn·əˌreɪt", "japanese_synonym":"尊敬（そんけい）する"},
    {"word":"articulate", "syllable_word":"ar·tic·u·late", "phonetic":"ɑːrˈtɪk·jʊˌleɪt", "japanese_synonym":"明瞭（めいりょう）な"},
    {"word":"bolster", "syllable_word":"bol·ster", "phonetic":"ˈboʊl·stər", "japanese_synonym":"支援（しえん）する"},
    {"word":"corroborate", "syllable_word":"cor·rob·o·rate", "phonetic":"kəˈrɑb·əˌreɪt", "japanese_synonym":"裏付ける（うらづける）"},
    {"word":"depict", "syllable_word":"de·pict", "phonetic":"dɪˈpɪkt", "japanese_synonym":"描く（えがく）"},
    {"word":"elucidate", "syllable_word":"e·lu·ci·date", "phonetic":"ɪˈluː·sɪˌdeɪt", "japanese_synonym":"明らかにする（あきらかにする）"},
    {"word":"foster", "syllable_word":"fos·ter", "phonetic":"ˈfɔ·stər", "japanese_synonym":"育成（いくせい）する"},
    {"word":"garner", "syllable_word":"gar·ner", "phonetic":"ˈɡɑr·nər", "japanese_synonym":"獲得（かくとく）する"},
    {"word":"hinder", "syllable_word":"hin·der", "phonetic":"ˈhɪn·dər", "japanese_synonym":"妨げる（さまたげる）"},
    {"word":"illuminate", "syllable_word":"il·lu·mi·nate", "phonetic":"ɪˈluː·məˌneɪt", "japanese_synonym":"照らす（てらす）"},
    {"word":"jostle", "syllable_word":"jos·tle", "phonetic":"ˈʤɑ·səl", "japanese_synonym":"押し合う（おしあう）"},
    {"word":"kaleidoscope", "syllable_word":"ka·lei·do·scope", "phonetic":"kəˈlaɪ·dəˌskoʊp", "japanese_synonym":"万華鏡（まんげきょう）"},
    {"word":"liaise", "syllable_word":"li·aise", "phonetic":"liˈeɪz", "japanese_synonym":"連絡を取る（れんらくをとる）"},
    {"word":"mitigate", "syllable_word":"mit·i·gate", "phonetic":"ˈmɪt·ɪˌgeɪt", "japanese_synonym":"軽減（けいげん）する"},
    {"word":"narrate", "syllable_word":"nar·rate", "phonetic":"ˈnær·eɪt", "japanese_synonym":"語る（かたる）"},
    {"word":"oscillate", "syllable_word":"os·cil·late", "phonetic":"ˈɑs·əˌleɪt", "japanese_synonym":"振動（しんどう）する"},
    {"word":"prolific", "syllable_word":"pro·lif·ic", "phonetic":"prəˈlɪf·ɪk", "japanese_synonym":"多産（たさん）の"},
    {"word":"quintessential", "syllable_word":"quin·tes·sen·tial", "phonetic":"ˌkwɪn·təˈsɛn·ʃəl", "japanese_synonym":"典型的（てんけいてき）な"},
    {"word":"resilient", "syllable_word":"re·sil·ient", "phonetic":"rɪˈzɪl·jənt", "japanese_synonym":"回復力（かいふくりょく）のある"},
    {"word":"stagnate", "syllable_word":"stag·nate", "phonetic":"ˈstægˌneɪt", "japanese_synonym":"停滞（ていたい）する"},
    {"word":"thrive", "syllable_word":"thrive", "phonetic":"θraɪv", "japanese_synonym":"繁栄（はんえい）する"},
    {"word":"ubiquitous", "syllable_word":"u·biq·ui·tous", "phonetic":"juːˈbɪk·wɪ·təs", "japanese_synonym":"至る所にある（いたるところにある）"},
    {"word":"vindicate", "syllable_word":"vin·di·cate", "phonetic":"ˈvɪn·dɪˌkeɪt", "japanese_synonym":"擁護（ようご）する"},
    {"word":"wane", "syllable_word":"wane", "phonetic":"weɪn", "japanese_synonym":"衰える（おとろえる）"},
    {"word":"xenophile", "syllable_word":"xe·no·phile", "phonetic":"ˈzɛn·əˌfaɪl", "japanese_synonym":"外国好き（がいこくずき）"},
    {"word":"yield", "syllable_word":"yield", "phonetic":"jiːld", "japanese_synonym":"生む（うむ）"},
    {"word":"zealot", "syllable_word":"zeal·ot", "phonetic":"ˈzɛl·ət", "japanese_synonym":"熱狂者（ねっきょうしゃ）"},

    {"word": "the", "syllable_word": "the", "phonetic": "ðə, ðiː", "japanese_synonym": "特定のものを指す時（とくていのものをさすとき）"},
    {"word": "of", "syllable_word": "of", "phonetic": "əv, ɒv", "japanese_synonym": "〜の（〜の）"},
    {"word": "and", "syllable_word": "and", "phonetic": "ænd", "japanese_synonym": "そして（そして）"},
    {"word": "to", "syllable_word": "to", "phonetic": "tuː, tə", "japanese_synonym": "〜へ（〜へ）"},
    {"word": "in", "syllable_word": "in", "phonetic": "ɪn", "japanese_synonym": "〜の中で（〜のなかで）"},
    {"word": "a", "syllable_word": "a", "phonetic": "ə, eɪ", "japanese_synonym": "一つの（ひとつの）"},
    {"word": "is", "syllable_word": "is", "phonetic": "ɪz", "japanese_synonym": "です、である（です、である）"},
    {"word": "that", "syllable_word": "that", "phonetic": "ðæt", "japanese_synonym": "それ（それ）"},
    {"word": "for", "syllable_word": "for", "phonetic": "fɔr", "japanese_synonym": "〜のために（〜のために）"},
    {"word": "it", "syllable_word": "it", "phonetic": "ɪt", "japanese_synonym": "それ（それ）"},

    {"word": "as", "syllable_word": "as", "phonetic": "æz", "japanese_synonym": "〜として（〜として）"},
    {"word": "was", "syllable_word": "was", "phonetic": "wəz", "japanese_synonym": "〜だった（〜だった）"},
    {"word": "with", "syllable_word": "with", "phonetic": "wɪð", "japanese_synonym": "〜と一緒に（〜といっしょに）"},
    {"word": "be", "syllable_word": "be", "phonetic": "biː", "japanese_synonym": "〜である（〜である）"},
    {"word": "by", "syllable_word": "by", "phonetic": "baɪ", "japanese_synonym": "〜によって（〜によって）"},
    {"word": "on", "syllable_word": "on", "phonetic": "ɒn", "japanese_synonym": "〜の上に（〜のうえに）"},
    {"word": "not", "syllable_word": "not", "phonetic": "nɒt", "japanese_synonym": "〜ではない（〜ではない）"},
    {"word": "he", "syllable_word": "he", "phonetic": "hiː", "japanese_synonym": "彼（かれ）"},
    {"word": "I", "syllable_word": "I", "phonetic": "aɪ", "japanese_synonym": "私（わたし）"},
    {"word": "this", "syllable_word": "this", "phonetic": "ðɪs", "japanese_synonym": "これ（これ）"},
    {"word": "are", "syllable_word": "are", "phonetic": "ɑr", "japanese_synonym": "〜です（〜です）"},
    {"word": "or", "syllable_word": "or", "phonetic": "ɔr", "japanese_synonym": "または（または）"},
    {"word": "his", "syllable_word": "his", "phonetic": "hɪz", "japanese_synonym": "彼の（かれの）"},
    {"word": "from", "syllable_word": "from", "phonetic": "frəm", "japanese_synonym": "〜から（〜から）"},
    {"word": "at", "syllable_word": "at", "phonetic": "æt", "japanese_synonym": "〜において（〜において）"},
    {"word": "which", "syllable_word": "which", "phonetic": "wɪtʃ", "japanese_synonym": "どれ（どれ）"},
    {"word": "but", "syllable_word": "but", "phonetic": "bʌt", "japanese_synonym": "しかし（しかし）"},
    {"word": "have", "syllable_word": "have", "phonetic": "hæv", "japanese_synonym": "持っている（もっている）"},
    {"word": "an", "syllable_word": "an", "phonetic": "æn", "japanese_synonym": "一つの（ひとつの）"},
    {"word": "had", "syllable_word": "had", "phonetic": "hæd", "japanese_synonym": "持っていた（もっていた）"},

    {"word": "they", "syllable_word": "they", "phonetic": "ðeɪ", "japanese_synonym": "彼ら（かれら）"},
    {"word": "you", "syllable_word": "you", "phonetic": "juː", "japanese_synonym": "あなた（あなた）"},
    {"word": "were", "syllable_word": "were", "phonetic": "wɜr", "japanese_synonym": "〜だった（〜だった）"},
    {"word": "their", "syllable_word": "their", "phonetic": "ðɛr", "japanese_synonym": "彼らの（かれらの）"},
    {"word": "one", "syllable_word": "one", "phonetic": "wʌn", "japanese_synonym": "一つ（ひとつ）"},
    {"word": "all", "syllable_word": "all", "phonetic": "ɔːl", "japanese_synonym": "全部（ぜんぶ）"},
    {"word": "we", "syllable_word": "we", "phonetic": "wiː", "japanese_synonym": "私たち（わたしたち）"},
    {"word": "can", "syllable_word": "can", "phonetic": "kæn", "japanese_synonym": "できる（できる）"},
    {"word": "her", "syllable_word": "her", "phonetic": "hɜr", "japanese_synonym": "彼女の（かのじょの）"},
    {"word": "has", "syllable_word": "has", "phonetic": "hæz", "japanese_synonym": "持っている（もっている）"},
    {"word": "there", "syllable_word": "there", "phonetic": "ðɛr", "japanese_synonym": "そこに（そこに）"},
    {"word": "been", "syllable_word": "been", "phonetic": "bɪn", "japanese_synonym": "〜だった（〜だった）"},
    {"word": "if", "syllable_word": "if", "phonetic": "ɪf", "japanese_synonym": "もし〜ならば（もし〜ならば）"},
    {"word": "more", "syllable_word": "more", "phonetic": "mɔr", "japanese_synonym": "もっと（もっと）"},
    {"word": "when", "syllable_word": "when", "phonetic": "wen", "japanese_synonym": "いつ（いつ）"},
    {"word": "will", "syllable_word": "will", "phonetic": "wɪl", "japanese_synonym": "〜するだろう（〜するだろう）"},
    {"word": "no", "syllable_word": "no", "phonetic": "noʊ", "japanese_synonym": "いいえ（いいえ）"},
    {"word": "out", "syllable_word": "out", "phonetic": "aʊt", "japanese_synonym": "外に（そとに）"},
    {"word": "do", "syllable_word": "do", "phonetic": "duː", "japanese_synonym": "する（する）"},
    {"word": "so", "syllable_word": "so", "phonetic": "soʊ", "japanese_synonym": "そう（そう）"},

    {"word": "up", "syllable_word": "up", "phonetic": "ʌp", "japanese_synonym": "上に（うえに）"},
    {"word": "what", "syllable_word": "what", "phonetic": "wɒt", "japanese_synonym": "何（なに）"},
    {"word": "about", "syllable_word": "about", "phonetic": "əˈbaʊt", "japanese_synonym": "〜について（〜について）"},
    {"word": "who", "syllable_word": "who", "phonetic": "huː", "japanese_synonym": "誰（だれ）"},
    {"word": "get", "syllable_word": "get", "phonetic": "ɡɛt", "japanese_synonym": "得る（える）"},
    {"word": "which", "syllable_word": "which", "phonetic": "wɪtʃ", "japanese_synonym": "どれ（どれ）"},
    {"word": "go", "syllable_word": "go", "phonetic": "ɡoʊ", "japanese_synonym": "行く（いく）"},
    {"word": "me", "syllable_word": "me", "phonetic": "miː", "japanese_synonym": "私に（わたしに）"},
    {"word": "make", "syllable_word": "make", "phonetic": "meɪk", "japanese_synonym": "作る（つくる）"},
    {"word": "can", "syllable_word": "can", "phonetic": "kæn", "japanese_synonym": "できる（できる）"},
    {"word": "like", "syllable_word": "like", "phonetic": "laɪk", "japanese_synonym": "〜のような（〜のような）"},
    {"word": "time", "syllable_word": "time", "phonetic": "taɪm", "japanese_synonym": "時間（じかん）"},
    {"word": "just", "syllable_word": "just", "phonetic": "ʤʌst", "japanese_synonym": "ちょうど（ちょうど）"},
    {"word": "him", "syllable_word": "him", "phonetic": "hɪm", "japanese_synonym": "彼に（かれに）"},
    {"word": "know", "syllable_word": "know", "phonetic": "noʊ", "japanese_synonym": "知る（しる）"},
    {"word": "take", "syllable_word": "take", "phonetic": "teɪk", "japanese_synonym": "取る（とる）"},
    {"word": "people", "syllable_word": "people", "phonetic": "ˈpiːpəl", "japanese_synonym": "人々（ひとびと）"},
    {"word": "into", "syllable_word": "into", "phonetic": "ˈɪntuː", "japanese_synonym": "〜の中に（〜のなかに）"},
    {"word": "year", "syllable_word": "year", "phonetic": "jɪr", "japanese_synonym": "年（とし）"},
    {"word": "your", "syllable_word": "your", "phonetic": "jɔr", "japanese_synonym": "あなたの（あなたの）"},

    {"word": "good", "syllable_word": "good", "phonetic": "ɡʊd", "japanese_synonym": "良い（よい）"},
    {"word": "some", "syllable_word": "some", "phonetic": "sʌm", "japanese_synonym": "いくつかの（いくつかの）"},
    {"word": "could", "syllable_word": "could", "phonetic": "kʊd", "japanese_synonym": "〜することができた（〜することができた）"},
    {"word": "them", "syllable_word": "them", "phonetic": "ðɛm", "japanese_synonym": "彼らを（かれらを）"},
    {"word": "see", "syllable_word": "see", "phonetic": "siː", "japanese_synonym": "見る（みる）"},
    {"word": "other", "syllable_word": "other", "phonetic": "ˈʌðər", "japanese_synonym": "他の（ほかの）"},
    {"word": "than", "syllable_word": "than", "phonetic": "ðæn", "japanese_synonym": "よりも（よりも）"},
    {"word": "then", "syllable_word": "then", "phonetic": "ðɛn", "japanese_synonym": "その後（そのご）"},
    {"word": "now", "syllable_word": "now", "phonetic": "naʊ", "japanese_synonym": "今（いま）"},
    {"word": "look", "syllable_word": "look", "phonetic": "lʊk", "japanese_synonym": "見る（みる）"},
    {"word": "only", "syllable_word": "only", "phonetic": "ˈoʊnli", "japanese_synonym": "ただ〜だけ（ただ〜だけ）"},
    {"word": "come", "syllable_word": "come", "phonetic": "kʌm", "japanese_synonym": "来る（くる）"},
    {"word": "its", "syllable_word": "its", "phonetic": "ɪts", "japanese_synonym": "それの（それの）"},
    {"word": "over", "syllable_word": "over", "phonetic": "ˈoʊvər", "japanese_synonym": "〜を越えて（〜をこえて）"},
    {"word": "think", "syllable_word": "think", "phonetic": "θɪŋk", "japanese_synonym": "考える（かんがえる）"},
    {"word": "also", "syllable_word": "also", "phonetic": "ˈɔlsoʊ", "japanese_synonym": "また（また）"},
    {"word": "back", "syllable_word": "back", "phonetic": "bæk", "japanese_synonym": "背中（せなか）"},
    {"word": "after", "syllable_word": "after", "phonetic": "ˈæftər", "japanese_synonym": "〜の後に（〜のあとに）"},
    {"word": "use", "syllable_word": "use", "phonetic": "juːz", "japanese_synonym": "使用する（しようする）"},
    {"word": "two", "syllable_word": "two", "phonetic": "tuː", "japanese_synonym": "二つ（ふたつ）"},

    {"word": "how", "syllable_word": "how", "phonetic": "haʊ", "japanese_synonym": "どのように（どのように）"},
    {"word": "our", "syllable_word": "our", "phonetic": "aʊər", "japanese_synonym": "私たちの（わたしたちの）"},
    {"word": "work", "syllable_word": "work", "phonetic": "wɜrk", "japanese_synonym": "仕事（しごと）"},
    {"word": "first", "syllable_word": "first", "phonetic": "fɜrst", "japanese_synonym": "最初の（さいしょの）"},
    {"word": "well", "syllable_word": "well", "phonetic": "wɛl", "japanese_synonym": "よく（よく）"},
    {"word": "way", "syllable_word": "way", "phonetic": "weɪ", "japanese_synonym": "方法（ほうほう）"},
    {"word": "even", "syllable_word": "even", "phonetic": "ˈiːvən", "japanese_synonym": "さえも（さえも）"},

    {"word": "algorithm", "syllable_word": "al·go·rithm", "phonetic": "ˈæl·gəˌrɪð·əm", "japanese_synonym": "アルゴリズム (あるごりずむ)"},
    {"word": "data", "syllable_word": "da·ta", "phonetic": "ˈdeɪ·tə", "japanese_synonym": "データ (でーた)"},
    {"word": "network", "syllable_word": "net·work", "phonetic": "ˈnet·wɜrk", "japanese_synonym": "ネットワーク (ねっとわーく)"},
    {"word": "system", "syllable_word": "sys·tem", "phonetic": "ˈsɪs·təm", "japanese_synonym": "システム (しすてむ)"},
    {"word": "technology", "syllable_word": "tech·nol·o·gy", "phonetic": "ˈtek·nɒl·ə·dʒi", "japanese_synonym": "テクノロジー (てくのろじー)"},
    {"word": "software", "syllable_word": "soft·ware", "phonetic": "ˈsɔft·wɛr", "japanese_synonym": "ソフトウェア (そふとうぇあ)"},
    {"word": "hardware", "syllable_word": "hard·ware", "phonetic": "ˈhɑrd·wɛr", "japanese_synonym": "ハードウェア (はーどうぇあ)"},
    {"word": "interface", "syllable_word": "in·ter·face", "phonetic": "ˈɪn·tərˌfeɪs", "japanese_synonym": "インターフェース (いんたーふぇーす)"},
    {"word": "application", "syllable_word": "ap·pli·ca·tion", "phonetic": "ˌæp·lɪˈkeɪ·ʃən", "japanese_synonym": "アプリケーション (あぷりけーしょん)"},
    {"word": "digital", "syllable_word": "dig·i·tal", "phonetic": "ˈdɪdʒ·ɪ·tl", "japanese_synonym": "デジタル (でじたる)"},
    {"word": "analysis", "syllable_word": "a·nal·y·sis", "phonetic": "əˈnæl·ɪ·sɪs", "japanese_synonym": "アナリシス (あなりしす)"},
    {"word": "simulation", "syllable_word": "sim·u·la·tion", "phonetic": "ˌsɪm·jʊˈleɪ·ʃən", "japanese_synonym": "シミュレーション (しみゅれーしょん)"},
    {"word": "optimization", "syllable_word": "op·ti·mi·za·tion", "phonetic": "ˌɒp·tɪ·maɪˈzeɪ·ʃən", "japanese_synonym": "オプティマイゼーション (おぷてぃまいぜーしょん)"},
    {"word": "integration", "syllable_word": "in·te·gra·tion", "phonetic": "ˌɪn·tɪˈgreɪ·ʃən", "japanese_synonym": "インテグレーション (いんてぐれーしょん)"},
    {"word": "automation", "syllable_word": "au·to·ma·tion", "phonetic": "ˌɔː·təˈmeɪ·ʃən", "japanese_synonym": "オートメーション (おーとめーしょん)"},
    {"word": "innovation", "syllable_word": "in·no·va·tion", "phonetic": "ˌɪn·əˈveɪ·ʃən", "japanese_synonym": "イノベーション (いのべーしょん)"},
    {"word": "cybersecurity", "syllable_word": "cy·ber·se·cu·ri·ty", "phonetic": "ˈsaɪ·bər·sɪˈkjʊə·rɪ·ti", "japanese_synonym": "サイバーセキュリティ (さいばーせきゅりてぃ)"},
    {"word": "database", "syllable_word": "da·ta·base", "phonetic": "ˈdeɪ·təˌbeɪs", "japanese_synonym": "データベース (でーたべーす)"},
    {"word": "framework", "syllable_word": "frame·work", "phonetic": "ˈfreɪm·wɜrk", "japanese_synonym": "フレームワーク (ふれーむわーく)"},
    {"word": "infrastructure", "syllable_word": "in·fra·struc·ture", "phonetic": "ˈɪn·frəˌstrʌk·tʃər", "japanese_synonym": "インフラストラクチャー (いんふらすとらくちゃー)"},
    {"word": "protocol", "syllable_word": "pro·to·col", "phonetic": "ˈproʊ·təˌkɒl", "japanese_synonym": "プロトコル (ぷろとこる)"},
    {"word": "bandwidth", "syllable_word": "band·width", "phonetic": "ˈbændˌwɪdθ", "japanese_synonym": "バンド幅 (ばんどはば)"},
    {"word": "encryption", "syllable_word": "en·cryp·tion", "phonetic": "ɪnˈkrɪp·ʃən", "japanese_synonym": "暗号化 (あんごうか)"},
    {"word": "firmware", "syllable_word": "firm·ware", "phonetic": "ˈfɜrmˌwɛr", "japanese_synonym": "ファームウェア (ふぁーむうぇあ)"},
    {"word": "cloud", "syllable_word": "cloud", "phonetic": "klaʊd", "japanese_synonym": "クラウド (くらうど)"},
    {"word": "scalability", "syllable_word": "scal·a·bil·i·ty", "phonetic": "ˌskeɪ·ləˈbɪl·ɪ·ti", "japanese_synonym": "スケーラビリティ (すけーらびりてぃ)"},
    {"word": "virtualization", "syllable_word": "vir·tu·al·i·za·tion", "phonetic": "ˌvɜr·tʃuˈæl·aɪˈzeɪ·ʃən", "japanese_synonym": "仮想化 (かそうか)"},
    {"word": "analytics", "syllable_word": "a·nal·y·tics", "phonetic": "əˈnæl·ɪ·tɪks", "japanese_synonym": "アナリティクス (あなりてぃくす)"},
    {"word": "e-commerce", "syllable_word": "e-com·merce", "phonetic": "ˈiːˌkɒm·ɜrs", "japanese_synonym": "電子商取引 (でんししょうとりひき)"},
    {"word": "server", "syllable_word": "serv·er", "phonetic": "ˈsɜr·vər", "japanese_synonym": "サーバー (さーばー)"},
    {"word": "epistemology", "syllable_word": "e·pis·te·mol·o·gy", "phonetic": "ɪˌpɪs·tɪˈmɒl·ə·dʒi", "japanese_synonym": "認識論 (にんしきろん)"},
    {"word": "heuristic", "syllable_word": "heu·ris·tic", "phonetic": "hjuːˈrɪs·tɪk", "japanese_synonym": "発見的 (はっけんてき)"},
    {"word": "paradigm", "syllable_word": "par·a·digm", "phonetic": "ˈpær·ə·daɪm", "japanese_synonym": "パラダイム (ぱらだいむ)"},
    {"word": "phenomenology", "syllable_word": "phe·nom·e·nol·o·gy", "phonetic": "fɪˌnɒm·əˈnɒl·ə·dʒi", "japanese_synonym": "現象学 (げんしょうがく)"},
    {"word": "pragmatism", "syllable_word": "prag·ma·tism", "phonetic": "ˈpræg·mə·tɪ·zəm", "japanese_synonym": "実用主義 (じつようしゅぎ)"},
    {"word": "symbiosis", "syllable_word": "sym·bi·o·sis", "phonetic": "ˌsɪm·baɪˈəʊ·sɪs", "japanese_synonym": "共生 (きょうせい)"},
    {"word": "teleology", "syllable_word": "tel·e·ol·o·gy", "phonetic": "ˌtel·iˈɒl·ə·dʒi", "japanese_synonym": "目的論 (もくてきろん)"},
    {"word": "transcendental", "syllable_word": "tran·scen·den·tal", "phonetic": "ˌtræn·senˈden·təl", "japanese_synonym": "超越的 (ちょうえつてき)"},
    {"word": "ubiquitous", "syllable_word": "u·biq·ui·tous", "phonetic": "juːˈbɪk·wɪ·təs", "japanese_synonym": "至る所にある (いたるところにある)"},
    {"word": "vernacular", "syllable_word": "ver·nac·u·lar", "phonetic": "vəˈnæk·jʊ·lər", "japanese_synonym": "土地言葉 (どちことば)"},
    {"word": "anomaly", "syllable_word": "a·nom·a·ly", "phonetic": "əˈnɒm·ə·li", "japanese_synonym": "異常 (いじょう)"},
    {"word": "cognizant", "syllable_word": "cog·ni·zant", "phonetic": "ˈkɒg·nɪ·zənt", "japanese_synonym": "認識している (にんしきしている)"},
    {"word": "dichotomy", "syllable_word": "di·chot·o·my", "phonetic": "daɪˈkɒt·ə·mi", "japanese_synonym": "二分法 (にぶんほう)"},
    {"word": "ethereal", "syllable_word": "e·the·re·al", "phonetic": "ɪˈθɪə·ri·əl", "japanese_synonym": "エーテリアル (えーてりある)"},
    {"word": "facet", "syllable_word": "fa·cet", "phonetic": "ˈfæs·ɪt", "japanese_synonym": "面 (めん)"},
    {"word": "gambit", "syllable_word": "gam·bit", "phonetic": "ˈgæm·bɪt", "japanese_synonym": "策略 (さくりゃく)"},
    {"word": "heterodox", "syllable_word": "het·er·o·dox", "phonetic": "ˈhet·ər·ə·dɒks", "japanese_synonym": "異端 (いたん)"},
    {"word": "idiomatic", "syllable_word": "id·i·o·mat·ic", "phonetic": "ˌɪd·i·əˈmæt·ɪk", "japanese_synonym": "熟語的 (じゅくごてき)"},
    {"word": "juxtapose", "syllable_word": "jux·ta·pose", "phonetic": "ˈdʒʌk·stə·pəʊz", "japanese_synonym": "並列する (へいれつする)"},
    {"word": "kinetic", "syllable_word": "ki·net·ic", "phonetic": "kɪˈnet·ɪk", "japanese_synonym": "運動の (うんどうの)"},
    {"word": "lucid", "syllable_word": "lu·cid", "phonetic": "ˈluː·sɪd", "japanese_synonym": "明快な (めいかいな)"},
    {"word": "metamorphosis", "syllable_word": "met·a·mor·pho·sis", "phonetic": "ˌmet·əˈmɔːr·fə·sɪs", "japanese_synonym": "変態 (へんたい)"},
    {"word": "nostalgia", "syllable_word": "nos·tal·gia", "phonetic": "nɒˈstæl·dʒə", "japanese_synonym": "郷愁 (きょうしゅう)"},
    {"word": "ontology", "syllable_word": "on·tol·o·gy", "phonetic": "ɒnˈtɒl·ə·dʒi", "japanese_synonym": "存在論 (そんざいろん)"},
    {"word": "paradox", "syllable_word": "par·a·dox", "phonetic": "ˈpær·ə·dɒks", "japanese_synonym": "逆説 (ぎゃくせつ)"},
    {"word": "quintessential", "syllable_word": "quin·tes·sen·tial", "phonetic": "ˌkwɪn·tɪˈsen·ʃəl", "japanese_synonym": "典型的な (てんけいてきな)"},
    {"word": "reverberate", "syllable_word": "re·ver·ber·ate", "phonetic": "rɪˈvɜː·bə·reɪt", "japanese_synonym": "反響する (はんきょうする)"},
        {"word": "surreal", "syllable_word": "sur·re·al", "phonetic": "səˈriː·əl", "japanese_synonym": "超現実的 (ちょうげんじつてき)"},
    {"word": "tacit", "syllable_word": "ta·cit", "phonetic": "ˈtæs·ɪt", "japanese_synonym": "暗黙の (あんもくの)"},
    {"word": "ubiquitous", "syllable_word": "u·biq·ui·tous", "phonetic": "juːˈbɪk·wɪ·təs", "japanese_synonym": "至る所にある (いたるところにある)"},
    {"word": "venerable", "syllable_word": "ven·er·a·ble", "phonetic": "ˈven·ər·ə·bl", "japanese_synonym": "尊敬される (そんけいされる)"},
    {"word": "whimsical", "syllable_word": "whim·si·cal", "phonetic": "ˈwɪm·zɪ·kəl", "japanese_synonym": "気まぐれな (きまぐれな)"},
    {"word": "xenophile", "syllable_word": "xe·no·phile", "phonetic": "ˈzen·ə·faɪl", "japanese_synonym": "外国好き (がいこくずき)"},
    {"word": "yield", "syllable_word": "yield", "phonetic": "jiːld", "japanese_synonym": "産出する (さんしゅつする)"},
    {"word": "zenith", "syllable_word": "ze·nith", "phonetic": "ˈzen·ɪθ", "japanese_synonym": "頂点 (ちょうてん)"},
    {"word": "aberration", "syllable_word": "ab·er·ra·tion", "phonetic": "ˌæb·əˈreɪ·ʃn", "japanese_synonym": "逸脱 (いつだつ)"},
    {"word": "benevolent", "syllable_word": "be·nev·o·lent", "phonetic": "bɪˈnev·əl·ənt", "japanese_synonym": "慈悲深い (じひぶかい)"},
    {"word": "conundrum", "syllable_word": "co·nun·drum", "phonetic": "kəˈnʌn·drəm", "japanese_synonym": "難問 (なんもん)"},
    {"word": "delineate", "syllable_word": "de·lin·e·ate", "phonetic": "dɪˈlɪn·i·eɪt", "japanese_synonym": "描写する (びょうしゃする)"},
    {"word": "efficacy", "syllable_word": "ef·fi·ca·cy", "phonetic": "ˈef·ɪ·kə·si", "japanese_synonym": "有効性 (ゆうこうせい)"},
    {"word": "fluctuate", "syllable_word": "fluc·tu·ate", "phonetic": "ˈflʌk·tʃu·eɪt", "japanese_synonym": "変動する (へんどうする)"},
    {"word": "grandiose", "syllable_word": "gran·di·ose", "phonetic": "ˈɡræn·di·əʊs", "japanese_synonym": "壮大な (そうだいな)"},
    {"word": "heterogeneous", "syllable_word": "het·er·o·ge·ne·ous", "phonetic": "ˌhet·ər·əˈdʒiː·ni·əs", "japanese_synonym": "異質な (いしつな)"},
    {"word": "immutable", "syllable_word": "im·mu·ta·ble", "phonetic": "ɪˈmjuː·tə·bl", "japanese_synonym": "不変の (ふへんの)"},
    {"word": "jovial", "syllable_word": "jo·vi·al", "phonetic": "ˈdʒəʊ·vi·əl", "japanese_synonym": "陽気な (ようきな)"},
    {"word": "kaleidoscope", "syllable_word": "ka·lei·do·scope", "phonetic": "kəˈlaɪ·dəˌskəʊp", "japanese_synonym": "万華鏡 (まんげきょう)"},
    {"word": "labyrinth", "syllable_word": "lab·y·rinth", "phonetic": "ˈlæb·ə·rɪnθ", "japanese_synonym": "迷宮 (めいきゅう)"},
    {"word": "magnanimous", "syllable_word": "mag·nan·i·mous", "phonetic": "mæɡˈnæn·ɪ·məs", "japanese_synonym": "寛大な (かんだいな)"},
    {"word": "nebulous", "syllable_word": "neb·u·lous", "phonetic": "ˈneb·jʊ·ləs", "japanese_synonym": "曖昧な (あいまいな)"},
    {"word": "trepidation", "syllable_word": "trep·i·da·tion", "phonetic": "ˌtrep·ɪˈdeɪ·ʃn", "japanese_synonym": "恐怖 (きょうふ)"},
    {"word": "unilateral", "syllable_word": "u·ni·lat·er·al", "phonetic": "ˌjuː·nɪˈlæt·ər·əl", "japanese_synonym": "一方的な (いっぽうてきな)"},
    {"word": "vindicate", "syllable_word": "vin·di·cate", "phonetic": "ˈvɪn·dɪ·keɪt", "japanese_synonym": "正当化する (せいとうかする)"},
    {"word": "whimsical", "syllable_word": "whim·si·cal", "phonetic": "ˈwɪm·zɪ·kəl", "japanese_synonym": "気まぐれな (きまぐれな)"},
    {"word": "xenogenesis", "syllable_word": "xe·no·gen·e·sis", "phonetic": "ˌzen·əˈdʒen·ɪ·sɪs", "japanese_synonym": "異種起源 (いしゅきげん)"},
    {"word": "yoke", "syllable_word": "yoke", "phonetic": "jəʊk", "japanese_synonym": "くびき (くびき)"},
    {"word": "zephyr", "syllable_word": "zeph·yr", "phonetic": "ˈzef·ər", "japanese_synonym": "西風 (にしかぜ)"},
    {"word": "acumen", "syllable_word": "ac·u·men", "phonetic": "ˈæk·jʊ·mən", "japanese_synonym": "鋭敏さ (えいびんさ)"},
    {"word": "bellicose", "syllable_word": "bel·li·cose", "phonetic": "ˈbel·ɪ·kəʊs", "japanese_synonym": "好戦的な (こうせんてきな)"},
    {"word": "circumspect", "syllable_word": "cir·cum·spect", "phonetic": "ˈsɜː·kəm·spekt", "japanese_synonym": "慎重な (しんちょうな)"},
    {"word": "disparate", "syllable_word": "dis·pa·rate", "phonetic": "ˈdɪs·pə·rət", "japanese_synonym": "異なる (ことなる)"},
    {"word": "exacerbate", "syllable_word": "ex·ac·er·bate", "phonetic": "ɪɡˈzæs·ər·beɪt", "japanese_synonym": "悪化させる (あっかさせる)"},
    {"word": "frivolous", "syllable_word": "friv·o·lous", "phonetic": "ˈfrɪv·əl·əs", "japanese_synonym": "軽薄な (けいはくな)"},
    {"word": "grandeur", "syllable_word": "gran·deur", "phonetic": "ˈɡræn·djʊər", "japanese_synonym": "壮大さ (そうだいさ)"},
    {"word": "incongruous", "syllable_word": "in·con·gru·ous", "phonetic": "ɪnˈkɒŋ·ɡru·əs", "japanese_synonym": "不釣り合いな (ふつりあいな)"},
    {"word": "juxtaposition", "syllable_word": "jux·ta·po·si·tion", "phonetic": "ˌdʒʌk·stə·pəˈzɪʃ·n", "japanese_synonym": "並列 (へいれつ)"},
    {"word": "kinesthetic", "syllable_word": "kin·es·thet·ic", "phonetic": "ˌkɪ·nesˈθet·ɪk", "japanese_synonym": "運動感覚の (うんどうかんかくの)"},
    {"word": "logorrhea", "syllable_word": "log·or·rhea", "phonetic": "ˌlɒɡ·əˈriː·ə", "japanese_synonym": "多弁症 (たべんしょう)"},
    {"word": "mellifluous", "syllable_word": "mel·lif·lu·ous", "phonetic": "məˈlɪf·lʊ·əs", "japanese_synonym": "甘美な (かんびな)"},
    {"word": "neologism", "syllable_word": "ne·ol·o·gism", "phonetic": "niːˈɒl·ə·dʒɪ·zəm", "japanese_synonym": "新語 (しんご)"},
    {"word": "ostentatious", "syllable_word": "os·ten·ta·tious", "phonetic": "ˌɒs·tenˈteɪ·ʃəs", "japanese_synonym": "見せびらかしの (みせびらかしの)"},
    {"word": "prognosticate", "syllable_word": "prog·nos·ti·cate", "phonetic": "prɒɡˈnɒs·tɪ·keɪt", "japanese_synonym": "予測する (よそくする)"},
    {"word": "quintessence", "syllable_word": "quin·tes·sence", "phonetic": "kwɪnˈtes·əns", "japanese_synonym": "精髄 (せいずい)"},
    {"word": "raconteur", "syllable_word": "rac·on·teur", "phonetic": "ˌræk·ɒnˈtɜːr", "japanese_synonym": "話術家 (わじゅつか)"},
    {"word": "serendipity", "syllable_word": "ser·en·dip·i·ty", "phonetic": "ˌser·ənˈdɪp·ɪ·ti", "japanese_synonym": "偶然の発見 (ぐうぜんのはっけん)"},
    {"word": "truculent", "syllable_word": "tru·cu·lent", "phonetic": "ˈtrʌk·jʊ·lənt", "japanese_synonym": "好戦的な (こうせんてきな)"},
    {"word": "unprecedented", "syllable_word": "un·prec·e·dent·ed", "phonetic": "ʌnˈpres·ɪ·den·tɪd", "japanese_synonym": "前例のない (ぜんれいのない)"},
    {"word": "veracity", "syllable_word": "ve·rac·i·ty", "phonetic": "vəˈræs·ɪ·ti", "japanese_synonym": "真実性 (しんじつせい)"},
    {"word": "wanton", "syllable_word": "wan·ton", "phonetic": "ˈwɒn·tən", "japanese_synonym": "無秩序な (むちつじょな)"},
    {"word": "xerophyte", "syllable_word": "xe·ro·phyte", "phonetic": "ˈzɪə·rə·faɪt", "japanese_synonym": "乾燥植物 (かんそうしょくぶつ)"},
    {"word": "yesteryear", "syllable_word": "yes·ter·year", "phonetic": "ˈjes·tə·jɪər", "japanese_synonym": "去年 (きょねん)"},
 {"word": "nebulous", "syllable_word": "neb·u·lous", "phonetic": "ˈneb·jʊ·ləs", "japanese_synonym": "曖昧な (あいまいな)"},
    {"word": "obfuscate", "syllable_word": "ob·fus·cate", "phonetic": "ˈɒb·fʌ·skeɪt", "japanese_synonym": "わかりにくくする (わかりにくくする)"},
    {"word": "pervasive", "syllable_word": "per·va·sive", "phonetic": "pəˈveɪ·sɪv", "japanese_synonym": "蔓延する (まんえんする)"},
    {"word": "quixotic", "syllable_word": "quix·ot·ic", "phonetic": "kwɪkˈsɒt·ɪk", "japanese_synonym": "非現実的な (ひげんじつてきな)"},
    {"word": "reciprocal", "syllable_word": "re·cip·ro·cal", "phonetic": "rɪˈsɪp·rə·kəl", "japanese_synonym": "相互の (そうごの)"},
    {"word": "synthesis", "syllable_word": "syn·the·sis", "phonetic": "ˈsɪn·θə·sɪs", "japanese_synonym": "合成 (ごうせい)"},
    {"word": "tangible", "syllable_word": "tan·gi·ble", "phonetic": "ˈtæn·dʒə·bl", "japanese_synonym": "有形の (ゆうけいの)"},
    {"word": "ubiquitous", "syllable_word": "u·biq·ui·tous", "phonetic": "juːˈbɪk·wɪ·təs", "japanese_synonym": "至る所にある (いたるところにある)"},
    {"word": "vacillate", "syllable_word": "vac·il·late", "phonetic": "ˈvæs·ɪ·leɪt", "japanese_synonym": "揺れ動く (ゆれうごく)"},
    {"word": "wistful", "syllable_word": "wist·ful", "phonetic": "ˈwɪst·fʊl", "japanese_synonym": "もの悲しい (ものかなしい)"},
    {"word": "xenophobia", "syllable_word": "xe·no·pho·bia", "phonetic": "ˌzen·əˈfəʊ·bi·ə", "japanese_synonym": "外国人恐怖症 (がいこくじんきょうふしょう)"},
    {"word": "yearn", "syllable_word": "yearn", "phonetic": "jɜːn", "japanese_synonym": "切望する (せつぼうする)"},
    {"word": "zealot", "syllable_word": "zeal·ot", "phonetic": "ˈzel·ət", "japanese_synonym": "熱狂者 (ねっきょうしゃ)"},
    {"word": "abrogate", "syllable_word": "ab·ro·gate", "phonetic": "ˈæb·rə·geɪt", "japanese_synonym": "廃止する (はいしする)"},
    {"word": "cacophony", "syllable_word": "ca·coph·o·ny", "phonetic": "kəˈkɒf·ə·ni", "japanese_synonym": "不協和音 (ふきょうわおん)"},
    {"word": "deleterious", "syllable_word": "del·e·te·ri·ous", "phonetic": "ˌdel·ɪˈtɪə·ri·əs", "japanese_synonym": "有害な (ゆうがいな)"},
    {"word": "ephemeral", "syllable_word": "ephem·er·al", "phonetic": "ɪˈfem·ər·əl", "japanese_synonym": "はかない (はかない)"},
    {"word": "facetious", "syllable_word": "fa·ce·tious", "phonetic": "fəˈsiː·ʃəs", "japanese_synonym": "ひょうきんな (ひょうきんな)"},
    {"word": "gregarious", "syllable_word": "gre·gar·i·ous", "phonetic": "ɡrɪˈɡeə·ri·əs", "japanese_synonym": "社交的な (しゃこうてきな)"},
    {"word": "hubris", "syllable_word": "hu·bris", "phonetic": "ˈhjuː·brɪs", "japanese_synonym": "傲慢 (ごうまん)"},
    {"word": "idiosyncratic", "syllable_word": "id·i·o·syn·crat·ic", "phonetic": "ˌɪd·i·əʊˈsɪŋ·krə·tɪk", "japanese_synonym": "特異な (とくいな)"},
    {"word": "jingoism", "syllable_word": "jin·go·ism", "phonetic": "ˈdʒɪŋ·gəʊ·ɪzəm", "japanese_synonym": "排外主義 (はいがいしゅぎ)"},
    {"word": "knell", "syllable_word": "knell", "phonetic": "nel", "japanese_synonym": "訃報の鐘 (ふほうのかね)"},
    {"word": "litigate", "syllable_word": "lit·i·gate", "phonetic": "ˈlɪt·ɪ·ɡeɪt", "japanese_synonym": "訴訟を起こす (そしょうをおこす)"},
    {"word": "misnomer", "syllable_word": "mis·no·mer", "phonetic": "ˈmɪs·nəʊ·mər", "japanese_synonym": "誤称 (ごしょう)"},
    {"word": "nonchalant", "syllable_word": "non·cha·lant", "phonetic": "ˌnɒn·ʃəˈlɑːnt", "japanese_synonym": "無関心な (むかんしんな)"},
    {"word": "oscillate", "syllable_word": "os·cil·late", "phonetic": "ˈɒs·ɪ·leɪt", "japanese_synonym": "振動する (しんどうする)"},
    {"word": "palpable", "syllable_word": "pal·pa·ble", "phonetic": "ˈpæl·pə·bl", "japanese_synonym": "明白な (めいはくな)"},
    {"word": "quell", "syllable_word": "quell", "phonetic": "kwel", "japanese_synonym": "鎮める (しずめる)"},
    {"word": "rescind", "syllable_word": "re·scind", "phonetic": "rɪˈsɪnd", "japanese_synonym": "撤回する (てっかいする)"},
    {"word": "sacrosanct", "syllable_word": "sac·ro·sanct", "phonetic": "ˈsæk·rəʊ·sæŋkt", "japanese_synonym": "神聖不可侵 (しんせいふかしん)"},
    {"word": "trepidation", "syllable_word": "trep·i·da·tion", "phonetic": "ˌtrep·ɪˈdeɪ·ʃn", "japanese_synonym": "恐怖 (きょうふ)"},
    {"word": "unilateral", "syllable_word": "u·ni·lat·er·al", "phonetic": "ˌjuː·nɪˈlæt·ər·əl", "japanese_synonym": "一方的な (いっぽうてきな)"},
    {"word": "vindicate", "syllable_word": "vin·di·cate", "phonetic": "ˈvɪn·dɪ·keɪt", "japanese_synonym": "正当化する (せいとうかする)"},
    {"word": "whimsical", "syllable_word": "whim·si·cal", "phonetic": "ˈwɪm·zɪ·kəl", "japanese_synonym": "気まぐれな (きまぐれな)"},
    {"word": "xenogenesis", "syllable_word": "xe·no·gen·e·sis", "phonetic": "ˌzen·əˈdʒen·ɪ·sɪs", "japanese_synonym": "異種起源 (いしゅきげん)"},
    {"word": "yoke", "syllable_word": "yoke", "phonetic": "jəʊk", "japanese_synonym": "くびき (くびき)"},
    {"word": "zephyr", "syllable_word": "zeph·yr", "phonetic": "ˈzef·ər", "japanese_synonym": "西風 (にしかぜ)"},
    {"word": "acumen", "syllable_word": "ac·u·men", "phonetic": "ˈæk·jʊ·mən", "japanese_synonym": "鋭敏さ (えいびんさ)"},
    {"word": "bellicose", "syllable_word": "bel·li·cose", "phonetic": "ˈbel·ɪ·kəʊs", "japanese_synonym": "好戦的な (こうせんてきな)"},
    {"word": "circumspect", "syllable_word": "cir·cum·spect", "phonetic": "ˈsɜː·kəm·spekt", "japanese_synonym": "慎重な (しんちょうな)"},
    {"word": "disparate", "syllable_word": "dis·pa·rate", "phonetic": "ˈdɪs·pə·rət", "japanese_synonym": "異なる (ことなる)"},
    {"word": "exacerbate", "syllable_word": "ex·ac·er·bate", "phonetic": "ɪɡˈzæs·ər·beɪt", "japanese_synonym": "悪化させる (あっかさせる)"},
    {"word": "frivolous", "syllable_word": "friv·o·lous", "phonetic": "ˈfrɪv·əl·əs", "japanese_synonym": "軽薄な (けいはくな)"},
    {"word": "grandeur", "syllable_word": "gran·deur", "phonetic": "ˈɡræn·djʊər", "japanese_synonym": "壮大さ (そうだいさ)"},
    {"word": "incongruous", "syllable_word": "in·con·gru·ous", "phonetic": "ɪnˈkɒŋ·ɡru·əs", "japanese_synonym": "不釣り合いな (ふつりあいな)"},
    {"word": "juxtaposition", "syllable_word": "jux·ta·po·si·tion", "phonetic": "ˌdʒʌk·stə·pəˈzɪʃ·n", "japanese_synonym": "並列 (へいれつ)"},
    {"word": "kinesthetic", "syllable_word": "kin·es·thet·ic", "phonetic": "ˌkɪ·nesˈθet·ɪk", "japanese_synonym": "運動感覚の (うんどうかんかくの)"},
    {"word": "logorrhea", "syllable_word": "log·or·rhea", "phonetic": "ˌlɒɡ·əˈriː·ə", "japanese_synonym": "多弁症 (たべんしょう)"},
    {"word": "mellifluous", "syllable_word": "mel·lif·lu·ous", "phonetic": "məˈlɪf·lʊ·əs", "japanese_synonym": "甘美な (かんびな)"},
    {"word": "neologism", "syllable_word": "ne·ol·o·gism", "phonetic": "niːˈɒl·ə·dʒɪ·zəm", "japanese_synonym": "新語 (しんご)"},
    {"word": "ostentatious", "syllable_word": "os·ten·ta·tious", "phonetic": "ˌɒs·tenˈteɪ·ʃəs", "japanese_synonym": "見せびらかしの (みせびらかしの)"},
    {"word": "prognosticate", "syllable_word": "prog·nos·ti·cate", "phonetic": "prɒɡˈnɒs·tɪ·keɪt", "japanese_synonym": "予測する (よそくする)"},
    {"word": "quintessence", "syllable_word": "quin·tes·sence", "phonetic": "kwɪnˈtes·əns", "japanese_synonym": "精髄 (せいずい)"},
    {"word": "raconteur", "syllable_word": "rac·on·teur", "phonetic": "ˌræk·ɒnˈtɜːr", "japanese_synonym": "話術家 (わじゅつか)"},
    {"word": "serendipity", "syllable_word": "ser·en·dip·i·ty", "phonetic": "ˌser·ənˈdɪp·ɪ·ti", "japanese_synonym": "偶然の発見 (ぐうぜんのはっけん)"},
    {"word": "truculent", "syllable_word": "tru·cu·lent", "phonetic": "ˈtrʌk·jʊ·lənt", "japanese_synonym": "好戦的な (こうせんてきな)"},
    {"word": "unprecedented", "syllable_word": "un·prec·e·dent·ed", "phonetic": "ʌnˈpres·ɪ·den·tɪd", "japanese_synonym": "前例のない (ぜんれいのない)"},
    {"word": "veracity", "syllable_word": "ve·rac·i·ty", "phonetic": "vəˈræs·ɪ·ti", "japanese_synonym": "真実性 (しんじつせい)"},
    {"word": "wanton", "syllable_word": "wan·ton", "phonetic": "ˈwɒn·tən", "japanese_synonym": "無秩序な (むちつじょな)"},
    {"word": "xerophyte", "syllable_word": "xe·ro·phyte", "phonetic": "ˈzɪə·rə·faɪt", "japanese_synonym": "乾燥植物 (かんそうしょくぶつ)"},
    {"word": "yesteryear", "syllable_word": "yes·ter·year", "phonetic": "ˈjes·tə·jɪər", "japanese_synonym": "去年 (きょねん)"},
    {"word": "zeitgeist", "syllable_word": "zeit·geist", "phonetic": "ˈzaɪt·ɡaɪst", "japanese_synonym": "時代精神 (じだいせいしん)"},
    {"word": "abnegation", "syllable_word": "ab·ne·ga·tion", "phonetic": "ˌæb·nɪˈɡeɪ·ʃn", "japanese_synonym": "自己否定 (じこひてい)"},
    {"word": "bucolic", "syllable_word": "bu·col·ic", "phonetic": "bjuːˈkɒl·ɪk", "japanese_synonym": "田園の (でんえんの)"},
    {"word": "chimerical", "syllable_word": "chi·mer·i·cal", "phonetic": "kaɪˈmer·ɪ·kəl", "japanese_synonym": "空想的な (くうそうてきな)"},
    {"word": "debacle", "syllable_word": "de·ba·cle", "phonetic": "dɪˈbɑː·kl", "japanese_synonym": "大失敗 (だいしっぱい)"},
    {"word": "esoteric", "syllable_word": "es·o·ter·ic", "phonetic": "ˌes·əˈter·ɪk", "japanese_synonym": "難解な (なんかいな)"},
    {"word": "fervor", "syllable_word": "fer·vor", "phonetic": "ˈfɜːr·vər", "japanese_synonym": "熱情 (ねつじょう)"},
    {"word": "garrulous", "syllable_word": "gar·ru·lous", "phonetic": "ˈɡær·ə·ləs", "japanese_synonym": "おしゃべりな (おしゃべりな)"},
    {"word": "hedonism", "syllable_word": "hed·o·nism", "phonetic": "ˈhed·ə·nɪ·zm", "japanese_synonym": "快楽主義 (かいらくしゅぎ)"},
    {"word": "idyllic", "syllable_word": "idyl·lic", "phonetic": "ɪˈdɪl·ɪk", "japanese_synonym": "田園詩的な (でんえんしつてきな)"},
    {"word": "jovial", "syllable_word": "jo·vi·al", "phonetic": "ˈdʒəʊ·vi·əl", "japanese_synonym": "陽気な (ようきな)"},
    {"word": "kinship", "syllable_word": "kin·ship", "phonetic": "ˈkɪn·ʃɪp", "japanese_synonym": "血縁関係 (けつえんかんけい)"},
    {"word": "ludicrous", "syllable_word": "lu·di·crous", "phonetic": "ˈluː·dɪ·krəs", "japanese_synonym": "ばかげた (ばかげた)"},
    {"word": "magnate", "syllable_word": "mag·nate", "phonetic": "ˈmæɡ·neɪt", "japanese_synonym": "大物 (おおもの)"},
    {"word": "narcissism", "syllable_word": "nar·cis·sism", "phonetic": "ˈnɑːr·sɪ·sɪ·zm", "japanese_synonym": "自己愛 (じこあい)"},
    {"word": "obsequious", "syllable_word": "ob·se·qui·ous", "phonetic": "əbˈsiː·kwi·əs", "japanese_synonym": "こびへつらう (こびへつらう)"},
    {"word": "panacea", "syllable_word": "pan·a·ce·a", "phonetic": "ˌpæn·əˈsiː·ə", "japanese_synonym": "万能薬 (ばんのうやく)"},
    {"word": "quandary", "syllable_word": "quan·da·ry", "phonetic": "ˈkwɒn·dər·i", "japanese_synonym": "窮地 (きゅうち)"},
    {"word": "raconteur", "syllable_word": "rac·on·teur", "phonetic": "ˌræk·ɒnˈtɜːr", "japanese_synonym": "話術家 (わじゅつか)"},
    {"word": "saccharine", "syllable_word": "sac·cha·rine", "phonetic": "ˈsæk·ər·ɪn", "japanese_synonym": "甘ったるい (あまったるい)"},
    {"word": "taciturn", "syllable_word": "tac·i·turn", "phonetic": "ˈtæs·ɪ·tɜːn", "japanese_synonym": "無口な (むくちな)"},
    {"word": "ubiquitous", "syllable_word": "u·biq·ui·tous", "phonetic": "juːˈbɪk·wɪ·təs", "japanese_synonym": "至る所にある (いたるところにある)"},
    {"word": "venerable", "syllable_word": "ven·er·a·ble", "phonetic": "ˈven·ər·ə·bl", "japanese_synonym": "尊敬される (そんけいされる)"},
    {"word": "wistful", "syllable_word": "wist·ful", "phonetic": "ˈwɪst·fʊl", "japanese_synonym": "もの悲しい (ものかなしい)"},
    {"word": "xenophilia", "syllable_word": "xe·no·phil·i·a", "phonetic": "ˌzen·əˈfɪl·i·ə", "japanese_synonym": "異文化好き (いぶんかずき)"},
    {"word": "yearn", "syllable_word": "yearn", "phonetic": "jɜːn", "japanese_synonym": "切望する (せつぼうする)"},
    {"word": "zeal", "syllable_word": "zeal", "phonetic": "ziːl", "japanese_synonym": "熱意 (ねつい)"},
    {"word": "accolade", "syllable_word": "ac·co·lade", "phonetic": "ˈæk·ə·leɪd", "japanese_synonym": "賞賛 (しょうさん)"},
    {"word": "ameliorate", "syllable_word": "a·mel·io·rate", "phonetic": "əˈmiː·li·ə·reɪt", "japanese_synonym": "改善する (かいぜんする)"},
    {"word": "capricious", "syllable_word": "ca·pri·cious", "phonetic": "kəˈprɪʃ·əs", "japanese_synonym": "気まぐれな (きまぐれな)"},
    {"word": "decadent", "syllable_word": "dec·a·dent", "phonetic": "ˈdek·ə·dənt", "japanese_synonym": "退廃的な (たいはいてきな)"},
    {"word": "egalitarian", "syllable_word": "e·gal·i·tar·i·an", "phonetic": "ɪˌɡæl·ɪˈteə·ri·ən", "japanese_synonym": "平等主義の (びょうどうしゅぎの)"},
    {"word": "fastidious", "syllable_word": "fas·tid·i·ous", "phonetic": "fæˈstɪd·i·əs", "japanese_synonym": "好みがうるさい (このみがうるさい)"},
    {"word": "glib", "syllable_word": "glib", "phonetic": "ɡlɪb", "japanese_synonym": "口先のうまい (くちさきのうまい)"},
    {"word": "hermetic", "syllable_word": "her·met·ic", "phonetic": "hɜːˈmet·ɪk", "japanese_synonym": "密閉された (みっぺいされた)"},
    {"word": "impetus", "syllable_word": "im·pe·tus", "phonetic": "ˈɪm·pɪ·təs", "japanese_synonym": "はずみ (はずみ)"},
    {"word": "jargon", "syllable_word": "jar·gon", "phonetic": "ˈdʒɑːr·ɡən", "japanese_synonym": "専門用語 (せんもんようご)"},
    {"word": "kudos", "syllable_word": "ku·dos", "phonetic": "ˈkuː·dɒs", "japanese_synonym": "名声 (めいせい)"},
    {"word": "languid", "syllable_word": "lan·guid", "phonetic": "ˈlæŋ·ɡwɪd", "japanese_synonym": "元気のない (げんきのない)"},
    {"word": "maverick", "syllable_word": "mav·er·ick", "phonetic": "ˈmæv·ər·ɪk", "japanese_synonym": "一匹狼 (いっぴきおおかみ)"},
    {"word": "nonplussed", "syllable_word": "non·plussed", "phonetic": "nɒnˈplʌst", "japanese_synonym": "当惑した (とうわくした)"},
    {"word": "orthodox", "syllable_word": "or·tho·dox", "phonetic": "ˈɔːr·θə·dɒks", "japanese_synonym": "正統派の (せいとうはの)"},


]